<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Student::insert([
            [
                'id' => 96,
                'filename' => 'implementation.png',
                'name' => 'Raheem Ali',
                'course' => 'ADCA',
                'date_of_admission' => '2024-02-14',
                'guardian_name' => 'me',
                'guardian_phone' => 3314132767,
                'mobile_no' => 3274651862,
                'email' => 'developerraheemali@gmail.com',
                'enrollment_no' => 'lkdha',
                'reference' => '9230092',
                'address' => 'Lahore',
                'admission_fees' => 239.00,
                'created_at' => '2024-09-03 21:13:12',
                'duration' => '12month',
                'paid_total' => '1309318572',
                'status' => 'active',
                'password' => 'fVw4Ub9O8K',
                'fee_status' => 'pending',
                'late_fee' => 'success'
            ],
            [
                'id' => 97,
                'filename' => 'WhatsApp_Image_2024-08-11_at_16_13_09_33e593ed-removebg-preview.png',
                'name' => 'saf',
                'course' => 'ADCA',
                'date_of_admission' => '2024-09-06',
                'guardian_name' => 'fsfsaff',
                'guardian_phone' => 23532423,
                'mobile_no' => 234234234,
                'email' => 'clashofclans8876239209@gmail.com',
                'enrollment_no' => '23423',
                'reference' => '2342',
                'address' => 'Laxmi Bazar Road',
                'admission_fees' => 233.00,
                'created_at' => '2024-09-05 18:54:55',
                'duration' => '3month',
                'paid_total' => '233',
                'status' => 'active',
                'password' => 'Lbkli9OAF4',
                'fee_status' => 'pending',
                'late_fee' => 'pending'
            ],
            [
                'id' => 98,
                'filename' => 'WhatsApp_Image_2024-08-01_at_00_33_22_a00b4b8a.jpg',
                'name' => 'sadas',
                'course' => 'ADCA',
                'date_of_admission' => '2024-07-17',
                'guardian_name' => 'fsafsafsafsaf',
                'guardian_phone' => 3433,
                'mobile_no' => 32432423432,
                'email' => '432@gmail.com',
                'enrollment_no' => '12123',
                'reference' => '343',
                'address' => 'dsfsdg',
                'admission_fees' => 2121.00,
                'created_at' => '2024-09-05 21:42:14',
                'duration' => '6month',
                'paid_total' => '2121',
                'status' => 'active',
                'password' => '85qTi30oZE',
                'fee_status' => 'pending',
                'late_fee' => 'pending'
            ],
            [
                'id' => 99,
                'filename' => 'WhatsApp_Image_2024-08-01_at_00_33_22_a00b4b8a1.jpg',
                'name' => 'sadas',
                'course' => 'ADCA',
                'date_of_admission' => '2024-07-17',
                'guardian_name' => 'fsafsafsafsaf',
                'guardian_phone' => 3433,
                'mobile_no' => 32432423432,
                'email' => '432@gmail.com',
                'enrollment_no' => '12123',
                'reference' => '343',
                'address' => 'dsfsdg',
                'admission_fees' => 2121.00,
                'created_at' => '2024-09-05 21:42:21',
                'duration' => '6month',
                'paid_total' => '2421',
                'status' => 'active',
                'password' => '85qTi30oZE',
                'fee_status' => 'pending',
                'late_fee' => 'success'
            ],
            [
                'id' => 102,
                'filename' => 'hospital1.png',
                'name' => 'efef',
                'course' => 'ADCA',
                'date_of_admission' => '2024-08-26',
                'guardian_name' => 'dsfdsf',
                'guardian_phone' => 332423,
                'mobile_no' => 234324,
                'email' => 'clashofclans8876239209@gmail.com',
                'enrollment_no' => 'dsfdsf',
                'reference' => '3423',
                'address' => 'Laxmi Bazar Road',
                'admission_fees' => 32312.00,
                'created_at' => '2024-09-05 21:48:50',
                'duration' => '3month',
                'paid_total' => '32312',
                'status' => 'active',
                'password' => 'd7Cgo3DlwP',
                'fee_status' => 'pending',
                'late_fee' => 'pending'
            ],
            [
                'id' => 109,
                'filename' => '(Bulk_1)_(Bulk_1)_Copy_of_Copy_of_temp.png',
                'name' => 'gfdg',
                'course' => 'DCA',
                'date_of_admission' => '0345-05-04',
                'guardian_name' => 'fggd',
                'guardian_phone' => 45643,
                'mobile_no' => 45435,
                'email' => '8822033082@gmail.com',
                'enrollment_no' => 'rt64',
                'reference' => '43',
                'address' => 't4ger',
                'admission_fees' => 5643.00,
                'created_at' => '2024-10-05 07:23:34',
                'duration' => '12month',
                'paid_total' => '5643',
                'status' => 'active',
                'password' => 'BHZvaDhYUZ',
                'fee_status' => 'pending',
                'late_fee' => 'pending'
            ],
            [
                'id' => 110,
                'filename' => 'llpi.png',
                'name' => 'hf',
                'course' => 'ADCA',
                'date_of_admission' => '2024-01-07',
                'guardian_name' => 'ghf',
                'guardian_phone' => 76876,
                'mobile_no' => 57,
                'email' => 'hih@gmail.com',
                'enrollment_no' => 'ho978',
                'reference' => '76',
                'address' => '8gvjh',
                'admission_fees' => 33.00,
                'created_at' => '2024-10-05 15:36:20',
                'duration' => '12month',
                'paid_total' => '45',
                'status' => 'active',
                'password' => 'X2MU1LtyUo',
                'fee_status' => 'pending',
                'late_fee' => 'success'
            ],
            [
                'id' => 111,
                'filename' => '(Bulk_1)_(Bulk_1)_Copy_of_Copy_of_temp1.png',
                'name' => 'eefe',
                'course' => 'ADCA',
                'date_of_admission' => '2024-01-01',
                'guardian_name' => 'grg',
                'guardian_phone' => 45435,
                'mobile_no' => 436534,
                'email' => 'dgg@gmail.com',
                'enrollment_no' => '645yhg',
                'reference' => '65',
                'address' => '5465',
                'admission_fees' => 654.00,
                'created_at' => '2024-10-14 06:47:34',
                'duration' => '12month',
                'paid_total' => '1210',
                'status' => 'active',
                'password' => 'GuYwvFyhSQ',
                'fee_status' => 'pending',
                'late_fee' => 'success'
            ],
            [
                'id' => 112,
                'filename' => 'images_(1).jpeg',
                'name' => 'bishal',
                'course' => 'ADCA',
                'date_of_admission' => '2024-01-17',
                'guardian_name' => 'rtf',
                'guardian_phone' => 434324,
                'mobile_no' => 32432,
                'email' => 'rfgf@gmail.com',
                'enrollment_no' => 'rert',
                'reference' => 'trg',
                'address' => '33343',
                'admission_fees' => 2.00,
                'created_at' => '2024-10-18 01:42:12',
                'duration' => '12month',
                'paid_total' => '100',
                'status' => 'active',
                'password' => 'BfhB4BFNzT',
                'fee_status' => 'pending',
                'late_fee' => 'success'
            ],
        ]);
    }
}
